baseURL = "https://coreyforjudge.netlify.com/"
languageCode = "en-us"
title = "Corey Larson for District Court Judge"
theme = "grayscale"
relativeURLs = true

[params]
copyright = "2018 Elect Corey Larson Judge (NP)"
address = "PO Box 2781 Longview, WA 98632"
phone = "(360) 218-1304"
email = "coreyjames13@hotmail.com"
description = "Vote Corey Larson for District Court Judge Position Two"
thumb_image = "img/thumb.png"


