[build]
publish = "public"
command = "hugo"

[build.environment]
HUGO_VERSION = "0.49"

[context.deploy-preview]
command = "hugo --minify"

[context.production]
command = "hugo --minify"

[context.production.environment]
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

